---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte da implantação local do NetApp Console. 
---
= Alterações recentes na implantação local do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console local deployment.



[[17-august-2026]]
== 17 de agosto de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, o Hyper-V introduz a seguinte melhoria:

*Restaurar backup de storage de objetos para um local alternativo*: Agora você pode restaurar VMs, arquivos e pastas do Hyper-V do storage de objetos para um local de armazenamento alternativo.

Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Saiba mais sobre como proteger cargas de trabalho do Hyper-V com o NetApp Backup and Recovery"].



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.08*: Esta versão inclui Trident Protect 26.08.
* *Repetições de backup*: Agora você pode habilitar as repetições de backup e configurar o número de tentativas de repetição e os intervalos entre as tentativas como configurações avançadas nas políticas de proteção do Kubernetes.
* *Sucesso parcial do backup*: Agora você pode configurar definições avançadas nas políticas de proteção do Kubernetes para continuar o backup mesmo quando recursos individuais falharem, permitindo que os trabalhos de backup sejam concluídos com sucesso parcial. Isso permite que você restaure os recursos de backup mesmo que alguns recursos falhem durante a operação de backup.
* *Backups consistentes com falhas e consistentes com VM*: o serviço Backup and Recovery para o NetApp Console agora permite configurar políticas de proteção que criam backups ou snapshots consistentes com falhas ou consistentes com VM. Você também pode personalizar como os congelamentos de VM são realizados durante a operação de proteção.
* *Reconectar o cluster Kubernetes após a alteração do IP do agente do Console*: o serviço de Backup and Recovery para o NetApp Console agora permite que você reconecte um cluster ao seu agente do Console se o endereço IP do agente for alterado.
* *Migrar cluster para o novo agente do Console*: O serviço NetApp Backup and Recovery para o NetApp Console agora permite que você migre um cluster para um novo agente do Console se o agente original falhar ou for excluído, garantindo proteção ininterrupta do aplicativo.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Saiba mais sobre como proteger cargas de trabalho do Kubernetes com NetApp Backup and Recovery"].



==== Aprimoramento das cargas de trabalho do Oracle Database

Nesta versão, as cargas de trabalho do Oracle Database introduzem as seguintes melhorias:

* *Restauração de Pluggable Database (PDB)*: Agora você pode restaurar pluggable databases (PDBs) e tablespaces de PDBs individuais, incluindo recuperação para um ponto no tempo.
* *Clonagem de banco de dados plugável (PDB)*: Agora você pode clonar um único PDB em um banco de dados de contêiner (CDB) de destino existente e, opcionalmente, excluir PDBs ao clonar um banco de dados de contêiner completo.


Para obter detalhes sobre como proteger cargas de trabalho do Oracle Database, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Saiba mais sobre como proteger as cargas de trabalho do Oracle Database com NetApp Backup and Recovery"].



[[10-august-2026]]
== 10 de agosto de 2026



[[netapp-console-local-deployment]]
=== NetApp Console implantação local



==== Apresentando a implantação local do NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Saiba como implantar localmente o NetApp Console"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Conheça as diferenças entre a implantação local do NetApp Console, o NetApp Console SaaS e o modo privado"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Melhorias gerais em NetApp Backup and Recovery

* *Suporte para implantação local do NetApp Console*: Esta versão do NetApp Backup and Recovery oferece suporte à implantação local do NetApp Console em status de prévia.
* *90 dias de retenção de tarefas*: O NetApp Backup and Recovery agora retém as informações das tarefas no Monitor de Tarefas por 90 dias.




==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta as seguintes melhorias:

* *Suporte para restauração em local alternativo para VMs SAN*: Agora você pode restaurar backups de VMs baseadas em SAN para um local alternativo.
* *Suporte para exclusão de vários backups*: Agora você pode excluir vários backups de uma só vez.


Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Suporte prévio para recursos isolados da internet*: Se você estiver executando o NetApp Backup and Recovery em uma implantação local do NetApp Console, você pode descobrir, proteger e restaurar recursos do Kubernetes isolados da internet. Este recurso está em prévia para este lançamento.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



==== Aprimoramentos nas cargas de trabalho do ONTAP Volumes

Nesta versão, as cargas de trabalho do ONTAP Volumes introduzem as seguintes melhorias:

* *Priorizar tarefas de restauração em relação aos backups*: Agora você pode priorizar tarefas de restauração em relação às tarefas de backup ao restaurar máquinas virtuais ou arquivos.
* *Descubra os sistemas ONTAP e volumes sem ativar o NetApp Backup and Recovery*: Agora você pode descobrir sistemas e volumes sem ativar o NetApp Backup and Recovery.


Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Visão geral das cargas de trabalho do Protect ONTAP Volumes"].



[[13-july-2026]]
== 13 de julho de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Suporte aprimorado para múltiplos buckets em todas as cargas de trabalho

NetApp Backup and Recovery agora oferece suporte à proteção das cargas de trabalho em um sistema com até 100 buckets em diferentes provedores de nuvem. ONTAP 9.19.1 ou posterior é necessário para oferecer suporte a mais de 6 buckets por sistema.

Para obter detalhes sobre NetApp Backup and Recovery, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Saiba mais sobre NetApp Backup and Recovery"].



[[15-june-2026]]
== 15 de junho de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.06*: Esta versão inclui Trident Protect 26.06.
* *Ignorar a criação de aplicativos durante a restauração*: Agora você pode ignorar a criação automática de objetos de recursos personalizados de aplicativos durante as operações de restauração. Isso reduz entradas desnecessárias no inventário de aplicativos.
* *Restaure os persistent volume claims da máquina virtual*: Ao restaurar aplicativos baseados em máquina virtual, agora você pode restaurar persistent volume claims individuais sem restaurar toda a máquina virtual, tornando a recuperação mais rápida quando discos ou volumes específicos são afetados por corrupção ou perda de dados.
* *Aprimoramentos no monitoramento de tarefas*: O monitoramento de tarefas agora oferece maior visibilidade das tarefas de proteção do Kubernetes. Você pode visualizar informações detalhadas sobre o status das tarefas e subtarefas e ver o armazenamento de destino usado por cada uma.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



[[08-june-2026]]
== 08 de junho de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Aprimoramentos nas cargas de trabalho do ONTAP Volumes

Nesta versão, as cargas de trabalho do ONTAP Volumes introduzem a seguinte melhoria:

*Suporte para storage de nuvem compatível com S3*: NetApp Backup and Recovery para cargas de trabalho de Volumes agora oferece suporte a backup em storage de nuvem compatível com S3.

Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Visão geral das cargas de trabalho do Protect ONTAP Volumes"].



==== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Aprimoramentos na restauração de arquivos e pastas para uma máquina virtual convidada*: Agora você pode restaurar arquivos e pastas de um snapshot no storage primário ou secundário para uma máquina virtual Windows convidada. Esse recurso agora é compatível com VMs CIFS e SAN.
* *Os grupos de proteção agora usam o agendamento de fuso horário do host*: Os grupos de proteção agora usam o fuso horário do host Hyper-V. Os grupos de proteção criados antes da introdução do agendamento de fuso horário do host continuam usando o horário configurado anteriormente (normalmente UTC). Para atualizar esses grupos de proteção para usar o fuso horário do host Hyper-V, você deve recriar os agendamentos. Consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho do Hyper-V"] para mais informações.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Fluxo de trabalho de proteção do Hyper-V com o NetApp Backup and Recovery"].



==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta a seguinte melhoria:

* *Os grupos de proteção agora usam o agendamento pelo fuso horário do host*: Os grupos de proteção agora usam o fuso horário do servidor VMware vCenter que os hospeda. Os grupos de proteção criados antes da introdução do agendamento pelo fuso horário do host continuam a ser executados no fuso horário configurado anteriormente (normalmente UTC). Para usar o fuso horário do vCenter, você deve recriar os agendamentos. Consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho VMware"] para mais informações.


Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].
